gpt-4o-mini:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4o-mini"
        body:
            max_tokens: 512

gpt-4:
    import: "./gpt4-chat.yaml"
    parameters:
        name: "gpt-4"

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

my-gemini:
    import: "./my-gemini.yaml"
    parameters:
        name: "my-gemini"

my-deepseek:
    import: "./my-deepseek.yaml"
    parameters:
        name: "my-deepseek"

my-qwen:
    import: "./my-qwen.yaml"
    parameters:
        name: "my-qwen"
